# Generated by Django 4.0.4 on 2022-05-18 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='reg_date',
        ),
        migrations.AddField(
            model_name='student',
            name='registrationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
    ]
